"""empty message

Revision ID: 0b217acf24d6
Revises: 7373ce08e0da
Create Date: 2016-03-22 14:50:37.895069

"""

# revision identifiers, used by Alembic.
revision = '0b217acf24d6'
down_revision = '7373ce08e0da'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diary', sa.Column('badge', sa.String(length=256), nullable=True))
    op.alter_column('diary', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.drop_column('diary', 'entryBadge')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diary', sa.Column('entryBadge', mysql.VARCHAR(length=256), nullable=True))
    op.alter_column('diary', 'active',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('diary', 'badge')
    ### end Alembic commands ###
