"""empty message

Revision ID: 569419ef8144
Revises: 4245d16f6062
Create Date: 2016-03-16 15:27:05.685834

"""

# revision identifiers, used by Alembic.
revision = '569419ef8144'
down_revision = '4245d16f6062'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.drop_column('user', 'badge')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('badge', mysql.VARCHAR(length=35), nullable=True))
    op.alter_column('user', 'is_admin',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    ### end Alembic commands ###
