"""empty message

Revision ID: 7373ce08e0da
Revises: 72d87c2a3610
Create Date: 2016-03-22 14:27:49.252341

"""

# revision identifiers, used by Alembic.
revision = '7373ce08e0da'
down_revision = '72d87c2a3610'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diary', sa.Column('entryBadge', sa.String(length=256), nullable=True))
    op.alter_column('diary', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diary', 'active',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('diary', 'entryBadge')
    ### end Alembic commands ###
