"""empty message

Revision ID: 80054742acde
Revises: 42c50bd03d25
Create Date: 2016-03-18 00:45:40.633890

"""

# revision identifiers, used by Alembic.
revision = '80054742acde'
down_revision = '42c50bd03d25'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    ### end Alembic commands ###
