"""empty message

Revision ID: 87b1b057885e
Revises: d0070cd3ec19
Create Date: 2016-03-15 12:53:12.114832

"""

# revision identifiers, used by Alembic.
revision = '87b1b057885e'
down_revision = 'd0070cd3ec19'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('badge', sa.String(length=35), nullable=True))
    op.alter_column('user', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_admin',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('user', 'badge')
    ### end Alembic commands ###
