"""empty message

Revision ID: 96a474b8a6cd
Revises: 9c3c4985e85f
Create Date: 2016-03-24 02:53:31.536803

"""

# revision identifiers, used by Alembic.
revision = '96a474b8a6cd'
down_revision = '9c3c4985e85f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diary', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diary', 'active',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    ### end Alembic commands ###
